#Heavy Weapons
@@assault_cannon = Weapon.send(:assault_cannon)
@@delfgun = Weapon.send(:delfgun)
@@heavybolter = Weapon.send(:heavybolter)
@@krakmissle = Weapon.send(:krakmissle)
@@lascannon = Weapon.send(:lascannon)
@@meltagun = Weapon.send(:meltagun)
@@plasma_gun = Weapon.send(:plasma_gun)
@@reaper_autocannon = Weapon.send(:reaper_autocannon)
@@heavyflamer = Weapon.send(:heavyflamer)
#Guns
@@boltgun = Weapon.send(:boltgun)
@@combibolter = Weapon.send(:combibolter)
@@eldar_reapergun = Weapon.send(:eldar_reapergun)
@@infernoboltgun = Weapon.send(:infernoboltgun)
@@stormbolter = Weapon.send(:stormbolter)
#Pistols
@@autopistol = Weapon.send(:autopistol)
@@boltpistol = Weapon.send(:boltpistol)
@@plasmapistol = Weapon.send(:plasmapistol)
#Melee
@@chainaxe = Weapon.send(:chainaxe)
@@chainsword = Weapon.send(:chainsword)
@@powersword = Weapon.send(:powersword)
@@powerfist = Weapon.send(:powerfirst)
@@poweraxe = Weapon.send(:poweraxe)
